"""跨层共享的类型、配置和异常。"""

from .config import DatabaseConfig, RuntimeConfig, configure_logging, load_dotenv
from .contracts import JsonObject, JsonPrimitive, JsonValue, SqlRow, SqlValue
from .errors import (
    AuthorizationError,
    BinderError,
    CatalogError,
    ConcurrencyError,
    ExecutionError,
    LexerError,
    YourSQLError,
    ParserError,
    RecoveryError,
    StorageError,
    TransactionError,
)
from .types import (
    Column,
    DataType,
    ExecutionResult,
    PageId,
    RowId,
    Schema,
    TableId,
    TableStats,
    Value,
    compare_values,
    decimal_to_json,
    json_safe,
    sql_truth,
    to_decimal,
)

__all__ = [
    "AuthorizationError",
    "BinderError",
    "CatalogError",
    "Column",
    "ConcurrencyError",
    "DataType",
    "DatabaseConfig",
    "RuntimeConfig",
    "ExecutionError",
    "ExecutionResult",
    "JsonObject",
    "JsonPrimitive",
    "JsonValue",
    "LexerError",
    "YourSQLError",
    "PageId",
    "ParserError",
    "RecoveryError",
    "RowId",
    "Schema",
    "SqlRow",
    "SqlValue",
    "StorageError",
    "TableId",
    "TableStats",
    "TransactionError",
    "Value",
    "compare_values",
    "configure_logging",
    "decimal_to_json",
    "json_safe",
    "load_dotenv",
    "sql_truth",
    "to_decimal",
]
