"""跨层共享的类型、配置和异常。"""

from yoursql.common.config import DatabaseConfig, RuntimeConfig, configure_logging, load_dotenv
from yoursql.common.codec import (
    MANUAL_CONTENT_TYPE,
    MANUAL_PAYLOAD_MAGIC,
    JsonPayloadCodec,
    ManualPayloadCodec,
    PayloadCodec,
    PayloadCodecError,
    PayloadCodecName,
    decode_payload,
    payload_codec,
    validate_payload_codec,
)
from yoursql.common.contracts import JsonObject, JsonPrimitive, JsonValue, SqlRow, SqlValue
from yoursql.common.errors import (
    AuthorizationError,
    BinderError,
    CatalogError,
    ExecutionError,
    LexerError,
    YourSQLError,
    ParserError,
    StorageError,
)
from yoursql.common.types import (
    Column,
    DataType,
    ExecutionResult,
    PageId,
    RowId,
    Schema,
    TableId,
    TableStats,
    Value,
    compare_values,
    sql_truth,
)

__all__ = [
    "AuthorizationError",
    "BinderError",
    "CatalogError",
    "Column",
    "DataType",
    "DatabaseConfig",
    "MANUAL_CONTENT_TYPE",
    "MANUAL_PAYLOAD_MAGIC",
    "RuntimeConfig",
    "ExecutionError",
    "ExecutionResult",
    "JsonObject",
    "JsonPrimitive",
    "JsonValue",
    "JsonPayloadCodec",
    "LexerError",
    "ManualPayloadCodec",
    "YourSQLError",
    "PageId",
    "ParserError",
    "PayloadCodec",
    "PayloadCodecError",
    "PayloadCodecName",
    "RowId",
    "Schema",
    "SqlRow",
    "SqlValue",
    "StorageError",
    "TableId",
    "TableStats",
    "Value",
    "compare_values",
    "configure_logging",
    "decode_payload",
    "load_dotenv",
    "payload_codec",
    "sql_truth",
    "validate_payload_codec",
]
